apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.celery.beat.pvc }}
  labels:
    app.kubernetes.io/name: {{ .Values.celery.beat.pvc }}
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  resources:
    requests:
      storage: {{ .Values.celery.beat.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
