{{- if .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.celery.grapharna.name }}-network-policy
  labels:
    app.kubernetes.io/name: {{ .Values.celery.grapharna.name }}-network-policy
    app.kubernetes.io/instance: {{ .Values.releaseName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.celery.grapharna.name }}
  policyTypes:
    - Egress
  egress:
    # RabbitMQ
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.rabbitmq.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.rabbitmq.port }}

    # Postgres
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.postgres.name }}
      ports:
        - protocol: TCP
          port: {{ .Values.postgres.port }}

    # DNS (CoreDNS)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: coredns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    {{- if .Values.global.networkPolicy.allowInternetEgress }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
    {{- end }}
{{- end }}
