apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rabbitmq.pvc }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage }}
