apiVersion: v1
name: grapharna-web-main-chart
version: 1.0.0-alpha
description: A webapp for predicting 3D RNA structures
home: /home
sources:
  - https://github.com/GraphaRNA-web/GraphaRNA-web
  - https://github.com/mjustynaPhD/GraphaRNA
maintainers:
  - name: Pawel Kelar
    email: pawel.kelar@student.put.poznan.pl
deprecated: false