apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  labels:
    app.kubernetes.io/name: letsencrypt-staging
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: grapharna-web
    app.kubernetes.io/managed-by: Helm
spec:
  selfSigned: {}
