# Generated by Django 5.2.3 on 2025-07-12 17:43

import datetime
import django.db.models.deletion
import uuid
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_structure", models.CharField(max_length=255)),
                ("seed", models.IntegerField()),
                ("job_name", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=webapp.models.default_expiration),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            7,
                            12,
                            17,
                            43,
                            48,
                            176059,
                            tzinfo=datetime.timezone.utc,
                        ),
                        null=True,
                    ),
                ),
                ("result_structure", models.CharField(max_length=255)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.job"
                    ),
                ),
            ],
        ),
    ]
