# Generated by Django 5.2.3 on 2025-07-12 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobresults",
            name="completed_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
