# Generated by Django 5.2.3 on 2025-07-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_alter_jobresults_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.TextField(
                choices=[("Q", "Queued"), ("P", "Processing"), ("F", "Finished")],
                default="q",
            ),
            preserve_default=False,
        ),
    ]
