# Generated by Django 5.2.3 on 2025-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="input_structure",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="jobresults",
            name="result_structure",
            field=models.FileField(upload_to=""),
        ),
    ]
