# Generated by Django 5.2.3 on 2025-07-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_alter_job_input_structure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
