# Generated by Django 5.2.3 on 2025-07-30 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_alter_job_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="alternative_conformations",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Value alternative_conformations can't be lower than 1",
                    ),
                    django.core.validators.MaxValueValidator(
                        5,
                        message="Value alternative_conformations can't be higher than 5",
                    ),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobresults",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.job"
            ),
        ),
    ]
