# Generated by Django 5.2.3 on 2025-09-05 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "webapp",
            "0009_rename_result_secondary_structure_jobresults_result_secondary_structure_dotseq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresults",
            name="f1",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value f1 can't be lower than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        1, message="Value f1 can't be higher than 1"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="jobresults",
            name="inf",
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value f1 can't be lower than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        1, message="Value f1 can't be higher than 1"
                    ),
                ],
            ),
        ),
    ]
