# Generated by Django 5.2.3 on 2025-09-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_jobresults_f1_jobresults_inf"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="sum_processing_time",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="jobresults",
            name="processing_time",
            field=models.DurationField(null=True),
        ),
    ]
