# Generated by Django 5.2.3 on 2025-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_job_sum_processing_time_jobresults_processing_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hashed_uid",
            field=models.CharField(
                editable=False, max_length=5, null=True, unique=True
            ),
        ),
    ]
