# Generated by Django 5.2.3 on 2025-10-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0012_job_hashed_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.TextField(
                choices=[
                    ("Q", "Queued"),
                    ("P", "Processing"),
                    ("F", "Finished"),
                    ("E", "Error"),
                ]
            ),
        ),
    ]
