# Generated by Django 5.2.3 on 2025-10-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0012_job_hashed_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.TextField(
                choices=[
                    ("S", "Submitted"),
                    ("Q", "Queued"),
                    ("R", "Running"),
                    ("C", "Completed"),
                    ("E", "Error"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="jobresults",
            name="result_tertiary_structure",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
