# Generated by Django 5.2.7 on 2025-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0013_alter_job_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="strand_separator",
            field=models.CharField(
                choices=[(" ", "Space"), ("-", "Hyphen"), ("N", "None")],
                default=" ",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
