# Generated by Django 5.2.3 on 2025-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_alter_jobresults_result_tertiary_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.TextField(
                choices=[
                    ("S", "Submitted"),
                    ("Q", "Queued"),
                    ("R", "Running"),
                    ("F", "Finished"),
                    ("E", "Error"),
                ]
            ),
        ),
    ]
