# Generated by Django 5.2.7 on 2025-11-12 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_job_strand_separator"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleStructures",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.job"
                    ),
                ),
            ],
        ),
    ]
