# Generated by Django 5.2.9 on 2025-12-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_examplestructures"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
    ]
