# Generated by Django 5.2.14 on 2026-05-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0016_job_finished_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="enable_dpm",
            field=models.BooleanField(default=False),
        ),
    ]
